---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: test-custom-plugin-sept3
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-custom-plugin-sept3 
  name: test-custom-plugin-sept3
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi